### ISSUE TITLE
Nose-randomly and setuptools don't get along

### ISSUE THREAD

**Issue by awood** [adamchainz/nose-randomly#11]
Trying to run `./setup.py nosetests` with the nose-randomly plugin installed causes setuptools to immediately. 

Here's the traceback:

```
% ./setup.py nosetests    
Traceback (most recent call last):
  File "./setup.py", line 304, in <module>
    test_suite='nose.collector',
  File "/usr/lib64/python2.7/distutils/core.py", line 137, in setup
    ok = dist.parse_command_line()
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 299, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/usr/lib64/python2.7/distutils/dist.py", line 467, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 609, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/usr/lib64/python2.7/distutils/dist.py", line 564, in _parse_command_opts
    (args, opts) = parser.getopt(args[1:])
  File "/usr/lib64/python2.7/distutils/fancy_getopt.py", line 253, in getopt
    self._grok_option_table()
  File "/usr/lib64/python2.7/distutils/fancy_getopt.py", line 171, in _grok_option_table
    "must be a string of length >= 2") % long
distutils.errors.DistutilsGetoptError: invalid long option 'with-randomly': must be a string of length >= 
2
```

My steps were:
1. `pip install nose-randomly`
2. set `test_suite='nose.collector'` in `setup()`
3. Run setup.py

**Comment by adamchainz** [comment]
This is weird. This plugin doesn't even actively add `with-randomly`, that's done by nose internally. Does any other nose plugin exhibit this behaviour? Have you checked the nose issue list?

**Comment by awood** [comment]
I've not seen this issue with `yanc`, `nose-capturestderr`, and/or `nose-xvfb`.  Looks like other people have seen similar issues though: https://github.com/kgrandis/nose-exclude/issues/4 and found some solutions.  See mat128's comments.
